### ISSUE TITLE
Wrong object being used in axios

### ISSUE THREAD

**Issue by jamesrollings** [connorjburton/adotime#15]
https://github.com/connorjburton/adotime/blob/d798c995aa46d344246cfcd612863ca58bcae37d/src/index.ts#L47
Should be `mergedAnswers.URL`

https://github.com/connorjburton/adotime/blob/d798c995aa46d344246cfcd612863ca58bcae37d/src/index.ts#L49
Should be `mergedAnswers.PAT`

As you are merging userConfig and inquirer answer objects together, so changing this would handle where the user has entered the PAT and/or URL in the inquirer prompt

**Comment by connorjburton** [comment]
Fixed in #16
